---
title: "ENVS 193DS - Final"
author: Scott Wagner
date: "June 4, 2025"
format: html
---

# Github Repository
https://github.com/ScottWag/ENVS-193DS_spring-2025_final

# Setup
```{r}
#| message: false
#| warning: false

#Load in packages
library(tidyverse)
library(here)
library(janitor)
library(readr)

```
# Problem 1. Research writing

## a. Transparent statistical methods

In part 1, they used a Pearson correlation to test the linear relationship between the two variables, distance from headwater and nitrogen load. In part 2, they used a one-way ANOVA to test for differences in average nitrogen load among the six different nitrogen sources.

## b. More information needed

Two additional tests/pieces of information that should be included to provide more context for the results would be a test for effect size (eta-squared) and a data visualization (boxplot or bar chart). An effect size test tells the viewer whether the observed differences are statistically significant, represented by a p-value. A data visualization helps communicate the patterns, variability, and group differences in a more accessible way by making the analysis visible.

## c. Suggestions for rewriting



# Problem 2. Data visualization

## a. Cleaning and summarizing

## b. Visualize the data

# Problem 3. Data analysis

## a. Response variable

## b. Purpose of study

## c. Difference in “seasons”

## d. Table of models

## e. Run the models

## f. Check the diagnostics

## g. Select the best model

## h. Visualize model predictions

## i. Write a caption for your figure

## j. Calculate model predictions 

## k. Interpret your results

# Problem 4. Affective and exploratory visualizations

## a. Comparing visualizations

## b. Sharing your affective visualization


